# Generated by Django 4.0.6 on 2022-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mobile_code_filter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='mobile_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
