# Generated by Django 4.0.6 on 2022-08-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_mobile_code_filter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='recipient_id',
        ),
    ]
