version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - 5432:5432
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      #app settings
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - EXTERNAL_MESSAGE_SENDER_SERVICE_SECRET_KEY={$EXTERNAL_MESSAGE_SENDER_SERVICE_SECRET_KEY}

      #db settings
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  celery:
    build: .
    command: celery -A app.celery_app worker -l info -B
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - rabbitmq
      - db